name: release
on:
  push:
    tags: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ GITHUB_REF }}-${{ hashFiles('**/*.gradle') }}
      - run: ./gradlew build publish curseforge
        env:
          MOD_VERSION: ${{ steps.vars.outputs.VERSION }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_MAVEN }}
          CURSEFORGE_API: ${{ secrets.CURSEFORGE_API }}
      - uses: actions/upload-artifact@v2
        with:
          name: fabric ${{ steps.vars.outputs.VERSION }}
          path: "./fabric/build/libs/wthit-**-fabric.jar"
      - uses: actions/upload-artifact@v2
        with:
          name: forge ${{ steps.vars.outputs.VERSION }}
          path: "./forge/build/libs/wthit-**-forge.jar"
      - uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./fabric/build/libs/wthit-**-fabric.jar","./forge/build/libs/wthit-**-forge.jar"]'
