name: release
on:
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
      - run: ./gradlew build curseforge modrinth publish --max-workers=1
        env:
          MOD_VERSION: ${{ steps.vars.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}
          CURSEFORGE_API: ${{ secrets.CURSEFORGE_API }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: wthit-${{ steps.vars.outputs.version }}
          path: "./platform/*/build/libs/**.jar"
      - uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: |
            [
              "./platform/*/build/libs/*[0-9.].jar",
              "./platform/*/build/libs/*[0-9.]-api.jar"
            ]
      - run: ./gradlew --stop
